{{- if not .Values.truenas.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scale-csi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scale-csi.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.truenas.apiKey }}
  api-key: {{ .Values.truenas.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.truenas.username }}
  username: {{ .Values.truenas.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.truenas.password }}
  password: {{ .Values.truenas.password | b64enc | quote }}
  {{- end }}
{{- end }}
