apiVersion: v2
name: scale-csi
description: Kubernetes CSI driver for TrueNAS SCALE storage
type: application
version: 0.0.0-dev
appVersion: "0.0.0-dev"
kubeVersion: ">=1.20.0-0"
home: https://github.com/GizmoTickler/scale-csi
sources:
  - https://github.com/GizmoTickler/scale-csi
maintainers:
  - name: GizmoTickler
keywords:
  - storage
  - csi
  - scale
  - zfs
  - nfs
  - iscsi
  - nvme
